#!/usr/bin/env python

import platform
import sys
import os

runtype=platform.architecture()

if (runtype[0]=='32bit'):
    sys.argv[0]='/l/arm2/saleae-tools/logic-i686/Logic'
    command = ' '.join(sys.argv)
    print command
    os.system(command)
else:
    sys.argv[0]='/l/arm2/saleae-tools/logic-x86_64/Logic'
    command = ' '.join(sys.argv)
    print command
    os.system(command)
